_wandb:
    value:
        cli_version: 0.28.1
        e:
            vxrmc3gaqc49qn76y47w2hm5vczqtsv3:
                codePath: src\train_models_wandb.py
                codePathLocal: src\train_models_wandb.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "283115515904"
                        used: "43560939520"
                email: newhaneul@naver.com
                executable: C:\Users\kkh\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 908c99f60fe3964168a0c9d98c5633f0af04d354
                    remote: https://github.com/KT-DINJAE-2026/KT-DINJAE-2026-AI.git
                host: DESKTOP-RRQN1AL
                memory:
                    total: "16837410816"
                os: Windows-10-10.0.26200-SP0
                program: d:\프로젝트\KT디지털인재장학생('26.03.20~present, KT)\지역사회 문제해결 프로젝트\KT-DINJAE-2026-AI\src\train_models_wandb.py
                python: CPython 3.10.3
                root: D:\프로젝트\KT디지털인재장학생('26.03.20~present, KT)\지역사회 문제해결 프로젝트\KT-DINJAE-2026-AI
                startedAt: "2026-08-01T08:28:35.819258Z"
                writerId: vxrmc3gaqc49qn76y47w2hm5vczqtsv3
        m:
            - "1": valid_0_l2
              "6":
                - 3
              "7":
                - 1
        python_version: 3.10.3
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 7
                - 13
                - 16
                - 25
                - 26
                - 62
                - 63
            "4": 3.10.3
            "5": 0.28.1
            "8":
                - 3
            "12": 0.28.1
            "13": windows-amd64
        visualize:
            Feature Importance:
                panel_config:
                    fieldSettings:
                        label: Feature
                        value: Importance
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Feature Importance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Feature Importance_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            model_b/feature_importance:
                panel_config:
                    fieldSettings:
                        label: feature
                        value: importance
                    panelDefId: wandb/bar/v0
                    stringSettings:
                        title: Model B Feature Importance
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: model_b/feature_importance_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
boosting_type:
    value: gbdt
colsample_bytree:
    value: 1
features:
    value:
        - route_id
        - board_stop_id
        - alight_stop_id
        - weekday
        - weather
        - bus_type_code
        - usertype_code
        - hour
        - is_holiday
        - headway_sec
        - seat_capacity
learning_rate:
    value: 0.05
max_depth:
    value: -1
metric:
    value:
        - regression
min_child_samples:
    value: 20
min_child_weight:
    value: 0.001
min_split_gain:
    value: 0
model:
    value: B_regressor
n_estimators:
    value: 1000
num_iterations:
    value: 1000
num_leaves:
    value: 31
num_threads:
    value: 4
objective:
    value: regression
random_state:
    value: null
reg_alpha:
    value: 0
reg_lambda:
    value: 0
subsample:
    value: 1
subsample_for_bin:
    value: 200000
subsample_freq:
    value: 0
train_rows:
    value: 736176
